import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080';

const nodeTypes = [
  'WEBHOOK_TRIGGER',
  'SCHEDULE_TRIGGER',
  'MANUAL_TRIGGER',
  'HTTP_REQUEST',
  'CONDITION',
  'DELAY',
  'GMAIL_SEND_EMAIL',
  'GITHUB_CREATE_ISSUE',
];

const configDefaults = {
  WEBHOOK_TRIGGER: {},
  SCHEDULE_TRIGGER: {},
  MANUAL_TRIGGER: {},
  HTTP_REQUEST: { method: 'GET', url: 'https://api.github.com', headers: {}, body: null },
  CONDITION: { path: 'input.amount', operator: 'gt', value: 1000 },
  DELAY: { seconds: 2 },
  GMAIL_SEND_EMAIL: {
    to: '{{input.email}}',
    subject: 'Workflow notification',
    body: 'Hello from Flow Builder',
  },
  GITHUB_CREATE_ISSUE: {
    owner: '',
    repo: '',
    title: 'Workflow issue for {{input.orderId}}',
    body: 'Generated by Flow Builder',
    labels: ['automation'],
  },
};

function App() {
  const [token, setToken] = useState(localStorage.getItem('flow_token') || '');
  const [view, setView] = useState('dashboard');
  const [selectedWorkflowId, setSelectedWorkflowId] = useState(null);

  const client = useMemo(() => createClient(token), [token]);

  function onAuth(auth) {
    localStorage.setItem('flow_token', auth.token);
    setToken(auth.token);
    setView('dashboard');
  }

  function logout() {
    localStorage.removeItem('flow_token');
    setToken('');
  }

  if (!token) {
    return <AuthScreen client={client} onAuth={onAuth} />;
  }

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">Flow Builder</div>
        <button className={view === 'dashboard' ? 'active' : ''} onClick={() => setView('dashboard')}>Dashboard</button>
        <button className={view === 'workflows' ? 'active' : ''} onClick={() => setView('workflows')}>Workflows</button>
        <button className={view === 'builder' ? 'active' : ''} onClick={() => setView('builder')}>Builder</button>
        <button className={view === 'integrations' ? 'active' : ''} onClick={() => setView('integrations')}>Integrations</button>
        <button className={view === 'runs' ? 'active' : ''} onClick={() => setView('runs')}>Runs</button>
        <button className="ghost" onClick={logout}>Sign out</button>
      </aside>
      <main className="main">
        {view === 'dashboard' && <Dashboard client={client} setView={setView} selectWorkflow={setSelectedWorkflowId} />}
        {view === 'workflows' && (
          <Workflows
            client={client}
            selectWorkflow={(id) => {
              setSelectedWorkflowId(id);
              setView('builder');
            }}
          />
        )}
        {view === 'builder' && (
          <Builder
            client={client}
            selectedWorkflowId={selectedWorkflowId}
            setSelectedWorkflowId={setSelectedWorkflowId}
          />
        )}
        {view === 'integrations' && <Integrations client={client} />}
        {view === 'runs' && <Runs client={client} selectedWorkflowId={selectedWorkflowId} />}
      </main>
    </div>
  );
}

function createClient(token) {
  async function request(path, options = {}) {
    const headers = { 'Content-Type': 'application/json', ...(options.headers || {}) };
    if (token) headers.Authorization = `Bearer ${token}`;
    const response = await fetch(`${API_URL}${path}`, {
      ...options,
      headers,
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
    });
    const text = await response.text();
    const data = text ? JSON.parse(text) : null;
    if (!response.ok) {
      throw new Error(data?.error || response.statusText);
    }
    return data;
  }
  return {
    get: (path) => request(path),
    post: (path, body) => request(path, { method: 'POST', body }),
    put: (path, body) => request(path, { method: 'PUT', body }),
    del: (path) => request(path, { method: 'DELETE' }),
  };
}

function AuthScreen({ client, onAuth }) {
  const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ name: '', email: '', password: '' });
  const [error, setError] = useState('');

  async function submit(event) {
    event.preventDefault();
    setError('');
    try {
      const path = mode === 'login' ? '/api/auth/login' : '/api/auth/register';
      onAuth(await client.post(path, form));
    } catch (err) {
      setError(err.message);
    }
  }

  return (
    <div className="auth-layout">
      <form className="auth-panel" onSubmit={submit}>
        <h1>Flow Builder</h1>
        <div className="segmented">
          <button type="button" className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Login</button>
          <button type="button" className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>Register</button>
        </div>
        {mode === 'register' && (
          <label>
            Name
            <input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />
          </label>
        )}
        <label>
          Email
          <input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />
        </label>
        <label>
          Password
          <input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} />
        </label>
        {error && <div className="error">{error}</div>}
        <button className="primary" type="submit">{mode === 'login' ? 'Login' : 'Create account'}</button>
      </form>
    </div>
  );
}

function Dashboard({ client, setView, selectWorkflow }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    client.get('/api/monitoring/dashboard').then(setData).catch((err) => setError(err.message));
  }, [client]);

  if (error) return <Notice tone="error" message={error} />;
  if (!data) return <Notice message="Loading dashboard..." />;

  return (
    <section>
      <Header title="Dashboard" action={<button className="primary" onClick={() => setView('workflows')}>New workflow</button>} />
      <div className="metric-grid">
        <Metric label="Workflows" value={data.workflows} />
        <Metric label="Published" value={data.published} />
        <Metric label="Runs" value={data.runs} />
        <Metric label="Succeeded" value={data.successfulRuns} />
        <Metric label="Failed" value={data.failedRuns} />
      </div>
      <h2>Recent Runs</h2>
      <Table
        rows={data.recentRuns || []}
        columns={[
          ['workflowName', 'Workflow'],
          ['status', 'Status'],
          ['triggerType', 'Trigger'],
          ['startedAt', 'Started'],
        ]}
        onRow={(run) => {
          selectWorkflow(run.workflowId);
          setView('runs');
        }}
      />
    </section>
  );
}

function Workflows({ client, selectWorkflow }) {
  const [workflows, setWorkflows] = useState([]);
  const [form, setForm] = useState({ name: '', description: '' });
  const [error, setError] = useState('');

  async function load() {
    setWorkflows(await client.get('/api/workflows'));
  }

  useEffect(() => {
    load().catch((err) => setError(err.message));
  }, [client]);

  async function create(event) {
    event.preventDefault();
    setError('');
    try {
      const workflow = await client.post('/api/workflows', form);
      setForm({ name: '', description: '' });
      await load();
      selectWorkflow(workflow.id);
    } catch (err) {
      setError(err.message);
    }
  }

  return (
    <section>
      <Header title="Workflows" />
      {error && <Notice tone="error" message={error} />}
      <form className="toolbar" onSubmit={create}>
        <input placeholder="Workflow name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />
        <input placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} />
        <button className="primary">Create</button>
      </form>
      <Table
        rows={workflows}
        columns={[
          ['name', 'Name'],
          ['status', 'Status'],
          ['updatedAt', 'Updated'],
        ]}
        onRow={(workflow) => selectWorkflow(workflow.id)}
      />
    </section>
  );
}

function Builder({ client, selectedWorkflowId, setSelectedWorkflowId }) {
  const [workflows, setWorkflows] = useState([]);
  const [graph, setGraph] = useState(null);
  const [selectedNode, setSelectedNode] = useState(null);
  const [nodeForm, setNodeForm] = useState(defaultNodeForm('HTTP_REQUEST'));
  const [edgeForm, setEdgeForm] = useState({ sourceNodeId: '', targetNodeId: '', edgeType: 'DEFAULT' });
  const [triggerForm, setTriggerForm] = useState({ cronExpression: '*/5 * * * *' });
  const [runInput, setRunInput] = useState('{"amount": 2500, "email": "user@example.com", "orderId": 100}');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  async function loadWorkflows() {
    const list = await client.get('/api/workflows');
    setWorkflows(list);
    if (!selectedWorkflowId && list[0]) setSelectedWorkflowId(list[0].id);
  }

  async function loadGraph(id = selectedWorkflowId) {
    if (!id) return;
    setGraph(await client.get(`/api/workflows/${id}/graph`));
  }

  useEffect(() => {
    loadWorkflows().catch((err) => setError(err.message));
  }, [client]);

  useEffect(() => {
    loadGraph().catch((err) => setError(err.message));
  }, [selectedWorkflowId, client]);

  async function addNode(event) {
    event.preventDefault();
    await mutate(async () => {
      await client.post(`/api/workflows/${selectedWorkflowId}/nodes`, {
        ...nodeForm,
        config: JSON.parse(nodeForm.configText || '{}'),
      });
      setNodeForm(defaultNodeForm(nodeForm.nodeType));
      await loadGraph();
    });
  }

  async function saveNode(node) {
    await mutate(async () => {
      await client.put(`/api/workflows/${selectedWorkflowId}/nodes/${node.id}`, {
        name: node.name,
        nodeType: node.nodeType,
        positionX: node.positionX,
        positionY: node.positionY,
        startNode: node.startNode,
        config: typeof node.config === 'string' ? JSON.parse(node.config) : node.config,
      });
      await loadGraph();
    });
  }

  async function addEdge(event) {
    event.preventDefault();
    await mutate(async () => {
      await client.post(`/api/workflows/${selectedWorkflowId}/edges`, {
        sourceNodeId: Number(edgeForm.sourceNodeId),
        targetNodeId: Number(edgeForm.targetNodeId),
        edgeType: edgeForm.edgeType,
      });
      setEdgeForm({ sourceNodeId: '', targetNodeId: '', edgeType: 'DEFAULT' });
      await loadGraph();
    });
  }

  async function createWebhook() {
    await mutate(async () => {
      await client.post(`/api/workflows/${selectedWorkflowId}/triggers/webhook`, {});
      await loadGraph();
    });
  }

  async function createSchedule(event) {
    event.preventDefault();
    await mutate(async () => {
      await client.post(`/api/workflows/${selectedWorkflowId}/triggers/schedule`, triggerForm);
      await loadGraph();
    });
  }

  async function workflowAction(action) {
    await mutate(async () => {
      await client.post(`/api/workflows/${selectedWorkflowId}/${action}`, {});
      await loadGraph();
    });
  }

  async function runNow() {
    await mutate(async () => {
      const run = await client.post(`/api/workflows/${selectedWorkflowId}/run`, { input: JSON.parse(runInput || '{}') });
      setNotice(`Run ${run.id} finished with ${run.status}`);
    });
  }

  async function mutate(fn) {
    setError('');
    setNotice('');
    try {
      await fn();
    } catch (err) {
      setError(err.message);
    }
  }

  const nodes = graph?.nodes || [];
  const editable = graph?.workflow?.status === 'DRAFT';

  return (
    <section>
      <Header
        title="Workflow Builder"
        action={
          <select value={selectedWorkflowId || ''} onChange={(e) => setSelectedWorkflowId(Number(e.target.value))}>
            <option value="">Select workflow</option>
            {workflows.map((workflow) => (
              <option key={workflow.id} value={workflow.id}>{workflow.name}</option>
            ))}
          </select>
        }
      />
      {error && <Notice tone="error" message={error} />}
      {notice && <Notice message={notice} />}
      {!graph ? (
        <Notice message="Create or select a workflow to begin." />
      ) : (
        <>
          <div className="toolbar">
            <StatusPill value={graph.workflow.status} />
            <button onClick={() => workflowAction('publish')}>Publish</button>
            <button onClick={() => workflowAction('pause')}>Pause</button>
            <button onClick={() => workflowAction('resume')}>Resume</button>
            <button className="primary" onClick={runNow}>Run now</button>
            <textarea className="run-input" value={runInput} onChange={(e) => setRunInput(e.target.value)} />
          </div>
          <div className="builder-grid">
            <GraphCanvas graph={graph} selectedNode={selectedNode} setSelectedNode={setSelectedNode} saveNode={saveNode} editable={editable} />
            <div className="builder-panel">
              <h2>Add Node</h2>
              <form onSubmit={addNode} className="stack">
                <input placeholder="Node name" value={nodeForm.name} onChange={(e) => setNodeForm({ ...nodeForm, name: e.target.value })} />
                <select
                  value={nodeForm.nodeType}
                  onChange={(e) => setNodeForm(defaultNodeForm(e.target.value))}
                >
                  {nodeTypes.map((type) => <option key={type} value={type}>{type}</option>)}
                </select>
                <label className="inline"><input type="checkbox" checked={nodeForm.startNode} onChange={(e) => setNodeForm({ ...nodeForm, startNode: e.target.checked })} /> Start node</label>
                <textarea value={nodeForm.configText} onChange={(e) => setNodeForm({ ...nodeForm, configText: e.target.value })} />
                <button disabled={!editable}>Add node</button>
              </form>
              <h2>Connect Nodes</h2>
              <form onSubmit={addEdge} className="stack">
                <select value={edgeForm.sourceNodeId} onChange={(e) => setEdgeForm({ ...edgeForm, sourceNodeId: e.target.value })}>
                  <option value="">Source</option>
                  {nodes.map((node) => <option key={node.id} value={node.id}>{node.name}</option>)}
                </select>
                <select value={edgeForm.targetNodeId} onChange={(e) => setEdgeForm({ ...edgeForm, targetNodeId: e.target.value })}>
                  <option value="">Target</option>
                  {nodes.map((node) => <option key={node.id} value={node.id}>{node.name}</option>)}
                </select>
                <select value={edgeForm.edgeType} onChange={(e) => setEdgeForm({ ...edgeForm, edgeType: e.target.value })}>
                  <option>DEFAULT</option>
                  <option>TRUE</option>
                  <option>FALSE</option>
                </select>
                <button disabled={!editable}>Add edge</button>
              </form>
              <h2>Triggers</h2>
              <button onClick={createWebhook}>Create webhook</button>
              <form onSubmit={createSchedule} className="inline-form">
                <input value={triggerForm.cronExpression} onChange={(e) => setTriggerForm({ cronExpression: e.target.value })} />
                <button>Schedule</button>
              </form>
              <TriggerList triggers={graph.triggers || []} />
            </div>
          </div>
          {selectedNode && <NodeEditor node={selectedNode} saveNode={saveNode} editable={editable} />}
        </>
      )}
    </section>
  );
}

function GraphCanvas({ graph, selectedNode, setSelectedNode, saveNode, editable }) {
  const [drag, setDrag] = useState(null);
  const nodes = graph.nodes || [];
  const nodeById = Object.fromEntries(nodes.map((node) => [node.id, node]));

  function move(event) {
    if (!drag) return;
    const node = nodes.find((item) => item.id === drag.id);
    if (!node) return;
    node.positionX = Math.max(20, event.clientX - drag.offsetX);
    node.positionY = Math.max(20, event.clientY - drag.offsetY);
    setSelectedNode({ ...node });
  }

  async function stop() {
    if (drag) {
      const node = nodes.find((item) => item.id === drag.id);
      if (node) await saveNode(node);
    }
    setDrag(null);
  }

  return (
    <div className="canvas" onPointerMove={move} onPointerUp={stop} onPointerLeave={stop}>
      <svg className="edges">
        {(graph.edges || []).map((edge) => {
          const source = nodeById[edge.sourceNodeId];
          const target = nodeById[edge.targetNodeId];
          if (!source || !target) return null;
          return (
            <g key={edge.id}>
              <line
                x1={source.positionX + 90}
                y1={source.positionY + 36}
                x2={target.positionX + 90}
                y2={target.positionY + 36}
                className={`edge edge-${edge.edgeType.toLowerCase()}`}
              />
              <text x={(source.positionX + target.positionX) / 2 + 90} y={(source.positionY + target.positionY) / 2 + 28}>{edge.edgeType}</text>
            </g>
          );
        })}
      </svg>
      {nodes.map((node) => (
        <button
          key={node.id}
          className={`node ${selectedNode?.id === node.id ? 'selected' : ''}`}
          style={{ left: node.positionX, top: node.positionY }}
          onClick={() => setSelectedNode(node)}
          onPointerDown={(event) => {
            if (!editable) return;
            setDrag({ id: node.id, offsetX: event.clientX - node.positionX, offsetY: event.clientY - node.positionY });
          }}
        >
          <span>{node.name}</span>
          <small>{node.nodeType}</small>
          {node.startNode && <b>START</b>}
        </button>
      ))}
    </div>
  );
}

function NodeEditor({ node, saveNode, editable }) {
  const [draft, setDraft] = useState({ ...node, configText: JSON.stringify(node.config || {}, null, 2) });
  const [error, setError] = useState('');

  useEffect(() => {
    setDraft({ ...node, configText: JSON.stringify(node.config || {}, null, 2) });
    setError('');
  }, [node]);

  async function submit() {
    try {
      setError('');
      await saveNode({ ...draft, config: JSON.parse(draft.configText || '{}') });
    } catch (err) {
      setError(err.message);
    }
  }

  return (
    <div className="drawer">
      <h2>Edit Node</h2>
      <div className="stack">
        <input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} />
        <select value={draft.nodeType} onChange={(e) => setDraft({ ...draft, nodeType: e.target.value })}>
          {nodeTypes.map((type) => <option key={type}>{type}</option>)}
        </select>
        <label className="inline"><input type="checkbox" checked={draft.startNode} onChange={(e) => setDraft({ ...draft, startNode: e.target.checked })} /> Start node</label>
        <textarea value={draft.configText} onChange={(e) => setDraft({ ...draft, configText: e.target.value })} />
        {error && <div className="error">{error}</div>}
        <button disabled={!editable} onClick={submit}>Save node</button>
      </div>
    </div>
  );
}

function Integrations({ client }) {
  const [items, setItems] = useState([]);
  const [gmail, setGmail] = useState({ clientId: '', clientSecret: '', refreshToken: '', fromEmail: '' });
  const [github, setGithub] = useState({ token: '', defaultOwner: '', defaultRepo: '' });
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  async function load() {
    setItems(await client.get('/api/integrations'));
  }

  useEffect(() => {
    load().catch((err) => setError(err.message));
  }, [client]);

  async function save(path, body) {
    setError('');
    setNotice('');
    try {
      await client.put(path, body);
      setNotice('Integration saved');
      await load();
    } catch (err) {
      setError(err.message);
    }
  }

  return (
    <section>
      <Header title="Integrations" />
      {error && <Notice tone="error" message={error} />}
      {notice && <Notice message={notice} />}
      <div className="split">
        <form className="stack" onSubmit={(e) => { e.preventDefault(); save('/api/integrations/gmail', gmail); }}>
          <h2>Gmail</h2>
          <input placeholder="Client ID" value={gmail.clientId} onChange={(e) => setGmail({ ...gmail, clientId: e.target.value })} />
          <input placeholder="Client secret" type="password" value={gmail.clientSecret} onChange={(e) => setGmail({ ...gmail, clientSecret: e.target.value })} />
          <input placeholder="Refresh token" type="password" value={gmail.refreshToken} onChange={(e) => setGmail({ ...gmail, refreshToken: e.target.value })} />
          <input placeholder="From email" value={gmail.fromEmail} onChange={(e) => setGmail({ ...gmail, fromEmail: e.target.value })} />
          <button className="primary">Save Gmail</button>
        </form>
        <form className="stack" onSubmit={(e) => { e.preventDefault(); save('/api/integrations/github', github); }}>
          <h2>GitHub</h2>
          <input placeholder="Personal access token" type="password" value={github.token} onChange={(e) => setGithub({ ...github, token: e.target.value })} />
          <input placeholder="Default owner" value={github.defaultOwner} onChange={(e) => setGithub({ ...github, defaultOwner: e.target.value })} />
          <input placeholder="Default repo" value={github.defaultRepo} onChange={(e) => setGithub({ ...github, defaultRepo: e.target.value })} />
          <button className="primary">Save GitHub</button>
        </form>
      </div>
      <h2>Configured</h2>
      <Table rows={items} columns={[['provider', 'Provider'], ['name', 'Name'], ['active', 'Active'], ['updatedAt', 'Updated']]} />
    </section>
  );
}

function Runs({ client, selectedWorkflowId }) {
  const [workflows, setWorkflows] = useState([]);
  const [workflowId, setWorkflowId] = useState(selectedWorkflowId || '');
  const [runs, setRuns] = useState([]);
  const [detail, setDetail] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    client.get('/api/workflows').then(setWorkflows).catch((err) => setError(err.message));
  }, [client]);

  useEffect(() => {
    if (!workflowId) return;
    client.get(`/api/workflows/${workflowId}/runs`).then(setRuns).catch((err) => setError(err.message));
  }, [workflowId, client]);

  async function openRun(run) {
    setDetail(await client.get(`/api/runs/${run.id}`));
  }

  return (
    <section>
      <Header title="Run History" />
      {error && <Notice tone="error" message={error} />}
      <select value={workflowId} onChange={(e) => setWorkflowId(e.target.value)}>
        <option value="">Select workflow</option>
        {workflows.map((workflow) => <option key={workflow.id} value={workflow.id}>{workflow.name}</option>)}
      </select>
      <Table
        rows={runs}
        columns={[
          ['id', 'Run'],
          ['status', 'Status'],
          ['triggerType', 'Trigger'],
          ['startedAt', 'Started'],
          ['endedAt', 'Ended'],
        ]}
        onRow={openRun}
      />
      {detail && (
        <div className="run-detail">
          <h2>Run {detail.run.id}</h2>
          <Table rows={detail.nodeRuns} columns={[['nodeName', 'Node'], ['nodeType', 'Type'], ['status', 'Status'], ['errorMessage', 'Error']]} />
          <h2>Logs</h2>
          <div className="logs">
            {detail.logs.map((log) => (
              <div key={log.id} className={`log log-${String(log.logLevel).toLowerCase()}`}>
                <span>{log.createdAt}</span>
                <b>{log.logLevel}</b>
                <p>{log.message}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </section>
  );
}

function TriggerList({ triggers }) {
  if (!triggers.length) return null;
  return (
    <div className="mini-list">
      {triggers.map((trigger) => (
        <div key={trigger.id}>
          <b>{trigger.triggerType}</b>
          {trigger.webhookPath && <code>{`${API_URL}/hooks/${trigger.webhookPath}`}</code>}
          {trigger.webhookSecret && <code>{trigger.webhookSecret}</code>}
          {trigger.cronExpression && <code>{trigger.cronExpression}</code>}
        </div>
      ))}
    </div>
  );
}

function defaultNodeForm(type) {
  return {
    name: type.replace(/_/g, ' ').toLowerCase(),
    nodeType: type,
    positionX: 80,
    positionY: 80,
    startNode: type.endsWith('TRIGGER'),
    configText: JSON.stringify(configDefaults[type] || {}, null, 2),
  };
}

function Header({ title, action }) {
  return (
    <div className="header">
      <h1>{title}</h1>
      {action}
    </div>
  );
}

function Metric({ label, value }) {
  return (
    <div className="metric">
      <span>{label}</span>
      <b>{value}</b>
    </div>
  );
}

function Notice({ message, tone = 'info' }) {
  return <div className={`notice ${tone}`}>{message}</div>;
}

function StatusPill({ value }) {
  return <span className={`status status-${String(value).toLowerCase()}`}>{value}</span>;
}

function Table({ rows, columns, onRow }) {
  if (!rows?.length) return <Notice message="No records yet." />;
  return (
    <div className="table-wrap">
      <table>
        <thead>
          <tr>{columns.map(([, label]) => <th key={label}>{label}</th>)}</tr>
        </thead>
        <tbody>
          {rows.map((row, index) => (
            <tr key={row.id || index} onClick={() => onRow?.(row)} className={onRow ? 'clickable' : ''}>
              {columns.map(([key]) => <td key={key}>{formatValue(row[key])}</td>)}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function formatValue(value) {
  if (value === null || value === undefined) return '';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return String(value);
}

createRoot(document.getElementById('root')).render(<App />);
